import type { SourceDefinition } from "./types";

export const SOURCES: SourceDefinition[] = [
  {
    id: "the-batch",
    name: "The Batch",
    category: "AI 与科技",
    kinds: ["article"],
    homepage: "https://www.deeplearning.ai/the-batch",
    discovery: { website: "https://www.deeplearning.ai/the-batch" },
    transcriptNotes: "只使用官方文章正文；文章不经过字幕环节。",
    enabled: true,
    phase: 1,
  },
  {
    id: "one-useful-thing",
    name: "One Useful Thing",
    category: "AI 与工作",
    kinds: ["article"],
    homepage: "https://www.oneusefulthing.org/",
    discovery: { website: "https://www.oneusefulthing.org/" },
    transcriptNotes: "只使用官方文章正文或官方 RSS 正文。",
    enabled: true,
    phase: 2,
  },
  {
    id: "mit-technology-review",
    name: "MIT Technology Review",
    category: "科技与未来趋势",
    kinds: ["article", "podcast"],
    homepage: "https://www.technologyreview.com/",
    discovery: { website: "https://www.technologyreview.com/" },
    transcriptNotes: "尊重订阅权限，绝不绕过付费墙。",
    enabled: true,
    phase: 2,
  },
  {
    id: "bloomberg-primer",
    name: "Bloomberg Primer",
    category: "商业与市场",
    kinds: ["video", "article"],
    homepage: "https://www.bloomberg.com/",
    discovery: { website: "https://www.bloomberg.com/" },
    transcriptNotes: "优先使用出版方正文，其次为官方字幕和 CC。",
    enabled: true,
    phase: 2,
  },
  {
    id: "stanford-gsb-view-from-the-top",
    name: "Stanford GSB View From The Top",
    category: "领军人物访谈",
    kinds: ["video", "podcast"],
    homepage: "https://www.gsb.stanford.edu/experience/learning/guest-speakers/view-top",
    discovery: {
      website:
        "https://www.gsb.stanford.edu/experience/learning/guest-speakers/view-top",
    },
    transcriptNotes: "交叉核对官网、YouTube 和 Podcast 版本。",
    enabled: true,
    phase: 2,
  },
  {
    id: "hbr-ideacast",
    name: "HBR IdeaCast",
    category: "商业与管理",
    kinds: ["podcast", "article"],
    homepage: "https://hbr.org/podcast/ideacast",
    discovery: { website: "https://hbr.org/podcast/ideacast" },
    transcriptNotes: "优先使用官方节目页和出版方文稿。",
    enabled: true,
    phase: 2,
  },
  {
    id: "knowledge-at-wharton",
    name: "Knowledge at Wharton",
    category: "商业分析",
    kinds: ["article", "podcast"],
    homepage: "https://knowledge.wharton.upenn.edu/",
    discovery: { website: "https://knowledge.wharton.upenn.edu/" },
    transcriptNotes: "使用官方文章或官方节目文稿。",
    enabled: true,
    phase: 2,
  },
  {
    id: "acquired",
    name: "Acquired",
    category: "公司历史与战略",
    kinds: ["podcast", "video"],
    homepage: "https://www.acquired.fm/",
    discovery: {
      website: "https://www.acquired.fm/",
      rss: "https://feeds.transistor.fm/acquired",
      applePodcasts: "https://podcasts.apple.com/us/podcast/acquired/id1050462261",
    },
    transcriptNotes: "使用时间戳前必须先匹配各平台长版内容。",
    enabled: true,
    phase: 1,
  },
  {
    id: "lennys-podcast",
    name: "Lenny’s Podcast",
    category: "产品与创业",
    kinds: ["podcast", "video"],
    homepage: "https://www.lennyspodcast.com/",
    discovery: { website: "https://www.lennyspodcast.com/" },
    transcriptNotes: "检查官方节目说明、Podcast RSS 和视频字幕。",
    enabled: true,
    phase: 2,
  },
  {
    id: "hidden-brain",
    name: "Hidden Brain",
    category: "心理学与社会",
    kinds: ["podcast", "article"],
    homepage: "https://www.hiddenbrain.org/",
    discovery: {
      website: "https://www.hiddenbrain.org/",
      rss: "https://feeds.simplecast.com/kwWc0lhf",
      applePodcasts: "https://podcasts.apple.com/us/podcast/hidden-brain/id1028908750",
      spotify: "https://open.spotify.com/show/20Gf4IAauFrfj7RBkjcWxh",
    },
    transcriptNotes: "官方文稿通常在节目发布后一周内上线。",
    enabled: true,
    phase: 1,
  },
  {
    id: "speaking-of-psychology",
    name: "Speaking of Psychology",
    category: "心理学",
    kinds: ["podcast", "article"],
    homepage: "https://www.apa.org/news/podcasts/speaking-of-psychology",
    discovery: {
      website: "https://www.apa.org/news/podcasts/speaking-of-psychology",
    },
    transcriptNotes: "优先使用 APA 官方文稿。",
    enabled: true,
    phase: 2,
  },
  {
    id: "freakonomics-radio",
    name: "Freakonomics Radio",
    category: "经济与社会",
    kinds: ["podcast", "article"],
    homepage: "https://freakonomics.com/series/freakonomics-radio/",
    discovery: {
      website: "https://freakonomics.com/series/freakonomics-radio/",
    },
    transcriptNotes: "优先使用官方节目文稿和 Podcast RSS。",
    enabled: true,
    phase: 2,
  },
];

export function getSource(sourceId: string) {
  return SOURCES.find((source) => source.id === sourceId);
}
